### ISSUE TITLE
How to use babelRC to pass the Parser option?

### ISSUE THREAD

**Issue by Sayid1** [trivago/prettier-plugin-sort-imports#10]
Your source code is follows
```javascript
 var defaultConfig = {
        sourceType: 'module',
        plugins: ['typescript', 'jsx'],
    };
    var babelConfig = core_1.loadOptions();
    var mergedOptions = lodash_1.merge(defaultConfig, babelConfig);
    var ast = parser_1.parse(code, mergedOptions);
```
.babelrc is example
```
{
  "parserOpts": {
    "plugins": ["classProperties"]
  }
}
```
merge value is 
```
 {
    sourceType: 'module',
    plugins: ['typescript', 'jsx'],
    parserOpts: {
        plugins: ['classProperties']
    }
};
```
The expected value should be follows
```
 {
    sourceType: 'module',
    plugins: ['typescript', 'jsx', 'classProperties'],
};
```

How do I set .babelrc to pass the Parser option correctly, or is there a problem with your source code?

Thank you very much

**Comment by byara** [comment]
With the release of [v2.0.1](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v2.0.1), this should be fixed. 
Either prettier will figure out the syntax correctly, or you can use `experimentalBabelParserPluginsList` in your `.prettierrc` to pass the correct parser name.

If there was still problems, you can of course re-open this issue.
