### ISSUE TITLE
Huge 27.4 MB install size

### ISSUE THREAD

**Issue by jaydenseric** [trivago/prettier-plugin-sort-imports#100]
`@trivago/prettier-plugin-sort-imports` (currently v3) has a huge 27.4 MB install size:

https://packagephobia.com/result?p=@trivago/prettier-plugin-sort-imports@3.0.0

This is unnecessarily inefficient. Personally, introducing this complexity and all the risks it entails to my projects outweighs the benefits and others might feel the same.

The first thing that jumps out is that all of `lodash` is being installed:

https://github.com/trivago/prettier-plugin-sort-imports/blob/97a6c7f52a299c24a168213c32422806d2c7ae9e/package.json#L42

`lodash` being used at all is a smell; almost always there is a native way to do the same simple things without introducing a complicated dependency. Any of the more complicated things `lodash` might genuinely help with, like deep comparison and cloning, are also a smell. Almost always there is a more elegant way to write the code to avoid deep comparisons and cloning. If there really is no way around doing those complicated operations, then never install the full `lodash` package to use just a few exports. Install separate lodash packages for each utility used to avoid installing all the unused stuff. Do these things right, and > 1 MB can be shaved off the install size and potentially runtime memory usage could be reduced.

It doesn't appear right to have the `@types/lodash` TypeScript types for `lodash` installed as a production dependency:

https://github.com/trivago/prettier-plugin-sort-imports/blob/97a6c7f52a299c24a168213c32422806d2c7ae9e/package.json#L40

839 kB could be shaved of the install size by moving it to dev dependencies:

https://packagephobia.com/result?p=@types/lodash@4.14.176

A low hanging fruit (which you have already identified in https://github.com/trivago/prettier-plugin-sort-imports/issues/96) is to prevent all the junk like tests, docs, examples, markdown files, etc. from being published:

https://unpkg.com/browse/@trivago/prettier-plugin-sort-imports@3.0.0/

Can any of these Babel dependencies be avoided or substituted for lighter options?

https://github.com/trivago/prettier-plugin-sort-imports/blob/97a6c7f52a299c24a168213c32422806d2c7ae9e/package.json#L35-L39

I haven't written a Prettier plugin before so I'm assuming there is no way to use the AST Prettier already generated? Does Prettier not accept an AST and do the string generation itself?

**Comment by ayusharma** [comment]
Hi @jaydenseric , First of all, thanks for the investigation. ❤️ 

> It doesn't appear right to have the @types/lodash TypeScript types for lodash installed as a production dependency:

yes, we will move it to the `devDependencies`. 

> Can any of these Babel dependencies be avoided or substituted for lighter options? 

We already thought about removing babel and use [`swc`](https://github.com/swc-project/swc) when we will have more time. 


> About lodash,

As the project is the development tool, I think it does not hurt much. We will look for other alternatives.

**Comment by ayusharma** [comment]
>  I'm assuming there is no way to use the AST Prettier already generated.
 As far as I know, prettier is an opinionated code formatter, it does not allow writing a plugin which is already built in the prettier.  So we can only write pre-processors to the prettier.  
 
 >  Does Prettier not accept an AST and do the string generation itself?
 
 It does not accept an AST and it accepts the generated code as a string.
