### ISSUE TITLE
Feature: Option to sort 'import * as lib from "lib"' first

### ISSUE THREAD

**Issue by Mattinton** [trivago/prettier-plugin-sort-imports#104]
It would be great if there was an option to sort `import * as lib from "lib"` at the top of the file.

For example

```javascript
import { LocationProvider } from "a-example-lib";
import * as bExampleLib from "b-example-lib";
import { RestaurantsProvider } from "c-example-lib";
```

to

```javascript
import * as bExampleLib from "b-example-lib";
import { LocationProvider } from "a-example-lib";
import { RestaurantsProvider } from "c-example-lib";
```

I tend to see these imports as globals or imports with the highest priority and I believe it would go a long way in keeping imports looking tidy

**Comment by byara** [comment]
Hey @Mattinton, this seems like a good idea, do you wanna send a PR for that?

**Comment by Mattinton** [comment]
@byara done!
