### ISSUE TITLE
Duplicate imports when regexes collide. 

### ISSUE THREAD

**Issue by isik-kaplan** [trivago/prettier-plugin-sort-imports#11]
Hello! 

For given config:  
```json
{
  "importOrder": ["^(.*)$", "^[./]"],
  "importOrderSeparation": true
}
```
`prettier-plugin-sort-imports` produces the same line multiple times. Not just that but for every other clashing regex it writes the matching lines again.

Not sure what the expected behavior would be, but it definitely is not creating multiple imports. 

One way to deal with this would be to start from the end and remove anything that has already been marked as used, so that for the above case, relative imports `./` would be at the end, end after that they wouldn't be re-inserted to the start of the list to be written. That way the import order would be decided. 

Given my above idea, it might also be better to allow the end user -in the config file with something like `importIgnoreClashingRegexOrder: "normal"|"reverse"`- to decide which way to start parsing from, shouldn't be hassle to change since all the library would do in that case would be to reverse the list.

**Comment by ayusharma** [comment]
It's a bug and we'll fix this from next release.

**Comment by isik-kaplan** [comment]
Lovely, thanks!

**Comment by byara** [comment]
Hey I closed the issue because we have now a pre-release. You can install this version and see if it fixes the issue.

`yarn add -D @trivago/prettier-plugin-sort-imports@pre-release`

Anyway, we are going to release a stable version soon.
