### ISSUE TITLE
Decorators problem for Angular project.

### ISSUE THREAD

**Issue by temofey1989** [trivago/prettier-plugin-sort-imports#12]
Hello,

I tried to use the plugin in the Angular project and got this error:

```
> prettier --write src/app/app.component.ts --config ./.prettierrc
src\app\app.component.ts
[error] src\app\app.component.ts: SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (5:0)
[error]    1 | import { isEmpty } from "lodash-es";
[error]    2 | 
[error]    3 | import { Component } from "@angular/core";
[error]    4 | 
[error]    5 | @Component({
[error]    6 |   selector: "app-root",
[error]    7 |   templateUrl: "./app.component.html",
[error]    8 |   styleUrls: ["./app.component.css"]
[error]    9 | })
[error]   10 | export class AppComponent {
[error]   11 |   title = "ng-prettier";
[error]   12 | 
[error]   13 |   get text(): string {
[error]   14 |     return isEmpty(this.title) ? "" : this.title;
[error]   15 |   }
[error]   16 | }
[error]   17 | 
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ng-prettier@0.0.0 format: `prettier --write src/app/app.component.ts --config ./.prettierrc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the ng-prettier@0.0.0 format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I use:
- Prettier: **2.2.0**
- Angular: **11.0.2**
- Typescript: **4.0.5**
- Plugin version: **1.3.0**

What am I doing wrong?
Is there any workaround?

Thanks a lot.

*NOTE*: No problem with React.

**Comment by byara** [comment]
@temofey1989 What is your prettier config in `.prettierrc`?

**Comment by temofey1989** [comment]
@byara, you are right.
After adding `"parser": "angular"` to the `.prettierrc` the command executed with no error.
This is my `.prettierrc` file:
```
{
  "tabWidth": 2,
  "printWidth": 120,
  "singleQuote": false,
  "useTabs": false,
  "bracketSpacing": true,
  "semi": true,
  "trailingComma": "none",
  "importOrder": [
    "^@angular/(.*)$",
    "^rxjs(.*)$",
    "^lodash(.*)$",
    "^[./]"
  ],
  "importOrderSeparation": true,
  "parser": "angular"
}
```

Nevertheless, now I have another problem...
Formatted code looks like this:
```
import { isEmpty } from "lodash-es"; import { Component } from "@angular/core"; @Component({ selector: "app-root",
templateUrl: "./app.component.html", styleUrls: ["./app.component.css"] }) export class AppComponent { title =
"ng-prettier"; get text(): string { return isEmpty(this.title) ? "" : this.title; } }
```
:smile:

**Comment by szaboge** [comment]
I have the same problem, now all the files look minimized.
```j
{
  parser: 'angular',
  printWidth: 120,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  bracketSpacing: false,
  jsxBracketSameLine: false,
  arrowParens: 'avoid',
  rangeStart: 0,
  rangeEnd: Infinity,
  requirePragma: false,
  insertPragma: false,
  proseWrap: 'preserve',
  importOrder: ['^rxjs/(.*)$', '^@angular/(.*)$', '^[./]'],
  importOrderSeparation: true,
}```

**Comment by byara** [comment]
@temofey1989 @szaboge could you also please provide your babel config?

**Comment by szaboge** [comment]
@byara I don't have custom babel config, I use default Angular CLI for the build.
Typescript compiler config:
```
{
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": true,
    "baseUrl": "src",
    "declaration": false,
    "downlevelIteration": true,
    "emitDecoratorMetadata": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "lib": ["es5", "es6", "es7", "dom"],
    "module": "es2020",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "outDir": "build",
    "pretty": true,
    "removeComments": false,
    "sourceMap": false,
    "strictNullChecks": false,
    "target": "es2015",
    "types": ["node", "jest"]
  }
```

**Comment by ShigotoMitame** [comment]
The angular formatter is only used for angular HTML, as suggested by the prettier docs:
>   - "angular" (same parser as "html", but also formats angular-specific syntax via angular-estree-parser) 
>
> https://prettier.io/docs/en/options.html#parser

You instead should be using typescript as the typescript code doesn't have any further modifications.

However, doing that returns you to the original error about experimental features. We discovered that changing this line 
https://github.com/trivago/prettier-plugin-sort-imports/blob/master/src/preprocessor.ts#L15
```
        plugins: ['typescript', 'jsx'],
```
to
```
        plugins: ['typescript', 'jsx', ['decorators', {'decoratorsBeforeExport': true}], 'classProperties'],
```
seemed to solve the issues with the unsupported syntax, but then ran into issues with the comments being stripped from files as #13 hasn't made it into a release yet.

**Comment by byara** [comment]
With the release of [v2.0.1](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v2.0.1), this should be fixed. 
Either prettier will figure out the syntax correctly, or you can use `experimentalBabelParserPluginsList` to pass the correct parser name.

If there was still problems, you can of course re-open this issue.

**Comment by ichepurnoy** [comment]
As of now, with prettier-plugin-sort-imports v3.2.0, I was able to solve it with the following config:

```
module.exports = {
  trailingComma: 'all',
  useTabs: false,
  tabWidth: 2,
  semi: true,
  singleQuote: true,
  bracketSpacing: true,
  importOrder: ['^@angular/(.*)$', '^(.*)ngrx(.*)$', '^(.*)module(.*)$', '^(.*)service(.*)$', '^(.*)guard(.*)$', '^(.*)pipe(.*)$', '^rxjs/(.*)$', '^[./]'],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  importOrderParserPlugins: ['typescript', "classProperties", "[\"decorators\", { \"decoratorsBeforeExport\": true }]"],
  parser: 'typescript',
  printWidth: 140,
};
```

Escaped double quotes inside `importOrderParserPlugins` are important, I tried changing them to single qoutes and failed.

**Comment by hminnnn** [comment]
I've got this error with prettier formatting when using sequelize typescript syntax
```
["ERROR" - 11:58:19 AM] Error formatting document.
["ERROR" - 11:58:19 AM] This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (25:0)
```

and adding this to .prettierrc solved my problem

`"importOrderParserPlugins": ["typescript", "decorators-legacy"]`
