### ISSUE TITLE
Decorators Experimental Syntax Error

### ISSUE THREAD

**Issue by mtpultz** [trivago/prettier-plugin-sort-imports#120]
**Your Environment**
 * **Prettier version**: 2.3.1
 * **node version** [12.x.x, 14.x.x]: 14.17.6
 * **package manager** [npm@7, pnpm@6, yarn@2]: yarn@2
 * **IDE** [VScode, Webstorm, CLI]: VSCode

**Describe the bug**

Installing the Prettier plugin using yarn (`yarn add -D @trivago/prettier-plugin-sort-imports`) formatting of the document starts throwing an error due to experimental syntax due to the use of decorators in Angular:

```
["ERROR" - 8:50:25 PM] Error formatting document.
["ERROR" - 8:50:25 PM] This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (32:0)
```

**To Reproduce**

1. Create an Nx workspace with an Angular application
2. Install sort imports `yarn add -D @trivago/prettier-plugin-sort-imports`
3. Add config to .prettierrc
4. Create a component
5. Attempt to format a document and watch the VSCode output

**Expected behavior**

A plugin that supports a variety of different libraries and frameworks should provide the plugin dev dependencies required for use especially when using TypeScript which doesn't require Babel for transpiling.

**Screenshots, code sample, etc**

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

```
{
  "singleQuote": true,
  "bracketSameLine": true,
  "importOrder": [
    "^@angular/(.*)$",
    "^rxjs/(.*)$",
    "<THIRD_PARTY_MODULES>",
    "^@bcgov/(.*)$",
    "^@core/(.*)$",
    "^@shared/(.*)$",
    "^[./]"
  ],
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true
}
```

**Error log**

```
["INFO" - 8:50:25 PM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 8:50:25 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 8:50:25 PM] Prettier Options:
{
  "filepath": "/Users/.../**.component.ts",
  "parser": "typescript",
  "useTabs": false,
  "tabWidth": 2,
  "singleQuote": true,
  "bracketSameLine": true,
  "attributeGroups": [
    "$ANGULAR_STRUCTURAL_DIRECTIVE",
    "^(id|name)$",
    "^class$",
    "$DEFAULT",
    "^aria-",
    "$ANGULAR_INPUT",
    "$ANGULAR_TWO_WAY_BINDING",
    "$ANGULAR_OUTPUT"
  ],
  "importOrder": [
    "^@angular/(.*)$",
    "^rxjs/(.*)$",
    "<THIRD_PARTY_MODULES>",
    "^@gov/(.*)$",
    "^@core/(.*)$",
    "^@shared/(.*)$",
    "^[./]"
  ],
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true
}
["ERROR" - 8:50:25 PM] Error formatting document.
["ERROR" - 8:50:25 PM] This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (32:0)
```

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇

**Comment by ratierd** [comment]
Hello @mtpultz.

I had the same issue and I think you just need to add `"importOrderParserPlugins": ["typescript", "decorators-legacy"],` in your prettier config file.

See [here](https://github.com/trivago/prettier-plugin-sort-imports#importorderparserplugins) for more details

**Comment by byara** [comment]
As @ratierd pointed out, you just need to add `importOrderParserPlugins` option in your rc file. I'll close the issue, but feel free to re-open if the issue still persists.

**Comment by nameer** [comment]
If anyone still scratching their head over tsx files, adding `jsx` to the list did it for me: `importOrderParserPlugins: ["typescript", "jsx", "decorators"]`.

**Comment by joey-ma** [comment]
> If anyone still scratching their head over tsx files, adding `jsx` to the list did it for me: `importOrderParserPlugins: ["typescript", "jsx", "decorators"]`.

thanks @nameer, I was confused why I was seeing all my `.tsx` files with `Parsing error:   prettier/prettier` now!

**Comment by beauspot** [comment]
Currently having same issue with typescript wen using decorators, prettier does not recognize the @Service()  (from typedi dependency) decorator on top of the service class. This is an express.js with typescript project. Please how do i fix this? This is the error I am having from my service: Parsing error: eslint[prettier/prettier](https://github.com/prettier/eslint-plugin-prettier#options), and attached to this issue is my code snippet.

![Image](https://github.com/user-attachments/assets/2d5fe98e-4f68-427b-8382-9880b3ae2522)

![Image](https://github.com/user-attachments/assets/7a2503a9-8eed-4734-a514-d686738c9024)
![Image](https://github.com/user-attachments/assets/e38f9a6b-f6b0-4ff5-9a06-d5c620f56203)
