### ISSUE TITLE
invaild use of require

### ISSUE THREAD

**Issue by crazyair** [trivago/prettier-plugin-sort-imports#137]
**Your Environment**
 * **Prettier version**: 2.x.x
 * **node version** [12.x.x, 14.x.x]:
 * **package manager**: [npm@7, pnpm@6, yarn@2]
 * **IDE**: [VScode, Webstorm, CLI]

**Describe the bug**

.prettierrc.js
```js
module.exports = {
    ...require('@my/prettier-config'),
};
```
 @my/prettier-config
```js
module.exports = {
...
 "importOrder": ["^@core/(.*)$", "^@server/(.*)$", "^@ui/(.*)$", "^[./]"],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
};
```
This is invalid

**To Reproduce**

**Expected behavior**

**Screenshots, code sample, etc**

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

**Error log**

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇

**Comment by crazyair** [comment]
help

**Comment by crazyair** [comment]
?

**Comment by crazyair** [comment]
@ayusharma help

**Comment by ayusharma** [comment]
Feel free to re-open if the issue still exists.
