### ISSUE TITLE
Allow to not sort local imports

### ISSUE THREAD

**Issue by moshfeu** [trivago/prettier-plugin-sort-imports#14]
Usually the order of 3rd parties doesn't matter but locally might be (when a module initiate something and return the initiated instance).

It could be nice to have a flag to prevent the local imports sorting.

**Comment by kovart** [comment]
Or it could be something that allows sorting inside a group

**Comment by ayusharma** [comment]
Hi,  Unfortunately, We can not stop sorting the imports, That is what for plugin designed. Thanks for the suggestion.
