### ISSUE TITLE
Some statements must be run before some imports but the prettier plugin puts them all in the end of the section.

### ISSUE THREAD

**Issue by ducqhl** [trivago/prettier-plugin-sort-imports#143]
**Is your feature request related to a problem?**
I used a library name dotenv and it required to run before any custom defined module in my project, but the sorter bring the line `dotenv.config()` to the end of the import section. 

**Describe the solution you'd like**
I wish to have some disable sort comment like lint rules
```js
// prettier-ignore
dotenv.config();
```

**Describe alternatives you've considered**

**Additional context**

**Comment by blutorange** [comment]
Not sure if it's the best solution, but right now, you could perhaps extract that statement into a separate file and import it via a side-effect import:

```javascript
// setup-environment.js
dotenv.config();

// other-file.js
import "./setup-environment.js";

import {} from ...;

// more code
```

Then if you use this fork https://www.npmjs.com/package/@ianvs/prettier-plugin-sort-imports which include the PR (#111) I made for not sorting side-effect imports, it should stay at the top.

**Comment by 8o8inCodes** [comment]
I've stumbled upon this issue and it's very annoying..

**Comment by ketansp** [comment]
I have a temporary work-around like this. Do mind the line at the end. Basically prettier ignore is applied on an empty line here. Import statements after that do get sorted properly.
```
import * as dotenv from 'dotenv';
dotenv.config();
// prettier-ignore

```

**Comment by Max-Starling** [comment]
After several attempts I've found perfect solution for me without any additional dependencies (less packages - less problems in the future with `package-lock.json` and legacy dependencies).

I wraped "pre-import" logic into modules (as suggested above):

```ts
// init-common.ts
import moduleAlias from "module-alias";

import initCommonLibrary from "@common/register";

moduleAlias.addAliases({
  "@common": `${__dirname}/../../../common`
});

initCommonLibrary();
```
```ts
// init-dotenv.ts
import dotenv from "dotenv";
import path from "path";

dotenv.config({
  path: path.resolve(__dirname, `../../.${process.env.NODE_ENV}.env`)
});
```
Then I added them to `importOrder` as `"init-(dotenv|common)$"` (more flexible variants like `init-(.*)` also should work): 
```json5
// .prettierrc.json
"importOrder": [
    "init-(dotenv|common)$",
    "^(@[^common][a-z]+|[a-z]+)",
    "^[a-z]+",
    "^@common/(.*)$",
    "^[./]"
  ],
"importOrderSeparation": true,
"importOrderSortSpecifiers": true,
"plugins": ["@trivago/prettier-plugin-sort-imports"]
```
And this it what I get after running `prettier . --write`
```ts
// result.ts
import "./src/modules/init-common";
import "./src/modules/init-dotenv";

import * as sentry from "@sentry/node";
import express from "express";

import { ContentType } from "@common/enums/http.enums";

import loggerMiddleware from "./src/middleware/logger.middleware";
import swagger from "./swagger";
```
