### ISSUE TITLE
decorators an class properties errors on a react project

### ISSUE THREAD

**Issue by giladv** [trivago/prettier-plugin-sort-imports#15]
when trying to run on a project with modern/ experimental js features it throws errors

```
packages/react-common/stores/UsersRepoStore.ts: SyntaxError: This experimental syntax requires enabling the parser plugin: 'classProperties' (10:22)
```
or
```
s[error] packages/react-common/stores/RecipesRepoStore.ts: SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): 'decorators-legacy, decorators' (9:1)
```

here is my setup:
```
module.exports = {
	singleQuote: true,
	printWidth: 120,
	useTabs: true,
	tabWidth: 2,
	semi: true,
	arrowParens: 'always',
	bracketSpacing: true,
	trailingComma: 'es5',
	importOrder: ['^\@co\-cooking', '^\.\.\/', '^\.\/(?!style)', '^\.\/style'],
	importOrderSeparation: true
};

```

tried using the typescript & babel parsers but it didn't work

**Comment by safareli** [comment]
Here is similar issue reported https://stackoverflow.com/questions/65284700/prettier-eslint-classproperties-parser-plugin-error

**Comment by safareli** [comment]
Has anyone found solution/workaround for this issue?

**Comment by ZhevnyakVladislav** [comment]
Hello everyone, I've solved this issue!
You just need to set option `"parser": "babel-ts"`, but sorting is breaking as in https://github.com/trivago/prettier-plugin-sort-imports/issues/6.

**Comment by ZhevnyakVladislav** [comment]
@ayusharma can you update lib for this parser as in https://github.com/trivago/prettier-plugin-sort-imports/issues/6?

**Comment by BenjaBobs** [comment]
I too am experiencing this.
Currently adding things to `.prettierignore` as a temporary solution.

**Comment by alzalabany** [comment]
same :/ hope it get fixed soon

**Comment by byara** [comment]
With the release of [v2.0.1](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v2.0.1), this should be fixed. 
Either prettier will figure out the syntax correctly, or you can use `experimentalBabelParserPluginsList` to pass the correct parser name.

If there was still problems, you can of course re-open this issue.
