### ISSUE TITLE
Configure number of newlines after imports?

### ISSUE THREAD

**Issue by GollyJer** [trivago/prettier-plugin-sort-imports#164]
We're using this eslint rule.
`import/newline-after-import": ["error", { "count": 2 }]`

It puts two newlines after imports, but when using prettier, it immediately overrides and sets the newline spacing to 1.

Could this be made configurable with your plugin?

**Comment by rushi** [comment]
This is happening to me too and it's quite annoying. Since I run the pluigin on save, it adds a new line. Then prettier runs via CLI or VS Code plugin and that removes it. It's a very annoying cycle

**Comment by ayusharma** [comment]
This is not possible to put multiple lines as prettier removes the extra line.
