### ISSUE TITLE
doesn't work on prettier 3.0

### ISSUE THREAD

**Issue by DetachHead** [trivago/prettier-plugin-sort-imports#171]
**Your Environment**
 * **Prettier version**: 3.0.0-alpha.0
 * **node version**: 16.11.1
 * **package manager**: npm@8
 * **IDE**: CLI

**Describe the bug**
when running with prettier `3.0.0-alpha.0`, the plugin does not seem to do anything

**To Reproduce**
1. install prettier 3.0.0-alpha.0
2. run prettier on a file with incorrectly sorted imports

**Expected behavior**
imports sorted

**Comment by IanVS** [comment]
I believe this plugin will now work with prettier 3.0.0-alpha.4 and above.
