### ISSUE TITLE
Multiple dollar sign $ in .vue files formats incorrectly

### ISSUE THREAD

**Issue by strickczq** [trivago/prettier-plugin-sort-imports#184]
**Your Environment**
 * **Prettier version**: 2.7.1
 * **node version**: 18.11.0
 * **package manager**: pnpm@7.13.4
 * **IDE**: VScode

**Describe the bug**

with `@trivago/prettier-plugin-sort-imports: 3.4.0`, code `$$(0);` will be formatted to `$(0);` in `.vue` files, which is unacceptable when using Vue3's `Reactivity Transform`

note that it works normally when:
- in `.js` and `.ts` files
- prettier with `@trivago/prettier-plugin-sort-imports: 3.3.1`
- prettier without `@trivago/prettier-plugin-sort-imports`

**To Reproduce**

there is a file `test.vue`
```vue
<script setup>
$$(0);
</script>
```

and then I run `prettier --plugin @trivago/prettier-plugin-sort-imports --write test.vue`

the file is formatted to
```vue
<script setup>
$(0);
</script>
```

interestingly
- `$` -> `$`
- `$$` -> `$`
- `$$$` -> `$$`
- `$$$$` -> `$$`

**Expected behavior**

the file `test.vue` should be unchanged
```vue
<script setup>
$$(0);
</script>
```

**Screenshots, code sample, etc**

<img width="599" alt="image" src="https://user-images.githubusercontent.com/11156420/198315148-17cd3af1-e4b3-4a68-be70-5d24206450bb.png">

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

prettier's default config with just `@trivago/prettier-plugin-sort-imports` plugin

**Error log**

N/A

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇

**Comment by michaelwilson-deswik** [comment]
This seems to also affects template literals which causes a change to the output of a string.

```vue
<script lang="ts">
const variableName = `$${true}`;
</script>
```
becomes
```vue
<script lang="ts">
const variableName = `${true}`;
</script>
```

**Comment by byara** [comment]
This should be addressed in the [v5](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v5.0.0). Please feel free to reopen in there is an issue.
