### ISSUE TITLE
@vue/compiler-sfc should be an optionalDependency instead of a peerDependency

### ISSUE THREAD

**Issue by transitive-bullshit** [trivago/prettier-plugin-sort-imports#188]
**Describe the bug**

This PR https://github.com/trivago/prettier-plugin-sort-imports/commit/157c7f9bf3b08e8b8c69320379a782236ffaf79b made it so v4.0.0 now has `@vue/compiler-sfc` as a peer dependency — which package managers will complain about.

Peer dependencies are supposed to be required in order for the package to work correctly. Instead, `@vue/compiler-sfc` should be marked as an optional dependency.

**Your Environment**
 * **Prettier version**:  2.8.0
 * **node version** 16.18.0
 * **package manager**: pnpm@7..17.0
 * **IDE**: CLI

**Error log**

```
WARN  Issues with peer dependencies found.
└─┬ @trivago/prettier-plugin-sort-imports 4.0.0
  └── ✕ missing peer @vue/compiler-sfc@3.x
Peer dependencies that should be installed:
  @vue/compiler-sfc@3.x  
```

**Contribute to @trivago/prettier-plugin-sort-imports**

- [x] I'm willing to fix this bug 🥇

**Comment by akomm** [comment]
Yes please. So many packages don't take it seriously. When installing packages you always get flooded by 1000 warnings and there is no way to detect when its really relevant, because so many don't set the dependencies correct.

**Comment by transitive-bullshit** [comment]
PR https://github.com/trivago/prettier-plugin-sort-imports/pull/189
