### ISSUE TITLE
TypeScript - import from declare module is moved to top

### ISSUE THREAD

**Issue by safareli** [trivago/prettier-plugin-sort-imports#19]
I have `global.d.ts` with contents:

```ts
declare module "*.scss" {
  const content: { [className: string]: string };
  export = content;
}

declare const env: {
  [key: string]: string;
};


declare module "path-browserify" {
  import * as path from "path";
  export = path;
}
```

and after running prettier on this file this happens:

```diff
+  import * as path from "path";
+
declare module "*.scss" {
  const content: { [className: string]: string };
  export = content;
}

declare const env: {
  [key: string]: string;
};


declare module "path-browserify" {
-  import * as path from "path";
  export = path;
}
```

**Comment by ayusharma** [comment]
That is the known issue, If you run prettier on everything then this can be the case. I would highly recommend using https://prettier.io/docs/en/ignore.html#ignoring-files-prettierignore

**Comment by ayusharma** [comment]
@byara do you have any other thoughts here?

**Comment by byara** [comment]
> @byara do you have any other thoughts here?

I came up with a solution, hopefully it solves this issue.

FYI @safareli

**Comment by safareli** [comment]
thanks!
