### ISSUE TITLE
Empty or missing script tag in Vue component causes error

### ISSUE THREAD

**Issue by adamDilger** [trivago/prettier-plugin-sort-imports#191]
**Your Environment**
 * **Prettier version**: 2.7.1
 * **node version** 16.13.1
 * **package manager**: npm@8, yarn@1.22
 * **IDE**: CLI

**Describe the bug**

When there is no script tag (or similarly, an empty script tag) in a vue SFC an error is thrown when running prettier on this file. 

**To Reproduce**

Using the example below, run `yarn run example examples/example.vue --config examples/.prettierrc`

**Expected behavior**

No error is thrown and only the template and style tags are formatted

**Screenshots, code sample, etc**

`examples/example.vue`

```
<template><div>HELLO WORLD</div></template>
<style> div   { color: red; } </style>
```

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

Default config

**Error log**

```
$ yarn run example examples/example.vue --config examples/.prettierrc
yarn run v1.22.19
$ yarn run compile
$ tsc
$ prettier --config ./examples/.prettierrc --plugin lib/src/index.js examples/example.vue --config examples/.prettierrc
[warn] jsxBracketSameLine is deprecated.
examples/example.vue[error] examples/example.vue: SyntaxError: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (2:0)
[error]   1 | <template><div>HELLO WORLD</div></template>
[error]   2 | <style>div { color: red; }</style>
[error]   3 |
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ x ] I'm willing to fix this bug 🥇 

I think I've tracked this down to the `vue-preprocessor.ts` file incorrectly passing the `code` variable to the processor when there is no script, instead of just returning `code` without any modifications. I can submit a PR shortly

**Comment by Daniel-Knights** [comment]
I'm experiencing similar. With this:

```vue
<template>
  <div id="loading"></div>
</template>

<script lang="ts" setup></script>
```

I get an error for `id` that says `Unexpected token, expected "</>/<=/>="`. Adding anything between the script tags fixes it.

Relevant portion of the stack trace: 

```bash
at Object.preprocessor (c:\Users\Dan\Desktop\note-boi\node_modules\@trivago\prettier-plugin-sort-imports\lib\src\preprocessors\preprocessor.js:15:24)
at Object.vuePreprocessor [as preprocess] (c:\Users\Dan\Desktop\note-boi\node_modules\@trivago\prettier-plugin-sort-imports\lib\src\preprocessors\vue-preprocessor.js:10:56)
```

**Comment by Tanimodori** [comment]
@byara Could you please release v4.0.1 to ship this fix? This issue is too annoying. Thank you.

**Comment by Tanimodori** [comment]
@ayusharma Could you please release v4.0.1? Thanks.

**Comment by g1eny0ung** [comment]
@ayusharma @byara It's been a long time since the latest release, and there have been a lot of significant fixes recently (e.g. #189, #192). The project I'm working on now is written in Vue, and it would be helpful if we could release a new version. Thanks a lot!

**Comment by SneakySensei** [comment]
> @ayusharma @byara It's been a long time since the latest release, and there have been a lot of significant fixes recently (e.g. #189, #192). The project I'm working on now is written in Vue, and it would be helpful if we could release a new version. Thanks a lot!

Agreed. @byara can you please publish a release?
