### ISSUE TITLE
@trivago/prettier-plugin-sort-imports@4.0.0" has unmet peer dependency "@vue/compiler-sfc@3.x"

### ISSUE THREAD

**Issue by VladimirMikulic** [trivago/prettier-plugin-sort-imports#195]
**Your Environment**
 * **Prettier version**: 2.8.1
 * **node version**: 18.12.1
 * **package manager**: yarn@1.22.19
 * **IDE**: VScode

**Describe the bug**

![Screenshot_20221216_174658](https://user-images.githubusercontent.com/35997844/208147794-ba00c18d-9d2a-43a3-9420-2e773d183d1b.png)

**To Reproduce**

1. npm init -y to create an empty project
2. Run yarn install @trivago/prettier-plugin-sort-imports
3. See yarn report the warning

**Expected behavior**

I'd expect warning not be shown. If `@vue/compiler-sfc@3.x` is required for this package to work, then it should be a dependency. Otherwise, it should be removed altogether.

**Contribute to @trivago/prettier-plugin-sort-imports**

- [x] I'm willing to fix this bug if I get input on @vue/compiler-sfc in this package 🥇

Thanks!

**Comment by Leomotors** [comment]
I think this is fixed in #189 just that they did not create release for it yet.

**Comment by VladimirMikulic** [comment]
Good point @Leomotors. Thanks.
@byara when can we expect release? :)
