### ISSUE TITLE
v4 of PrettierPluginSortImports moves ngAnnotate 'ngInject' within the files as if they are imports

### ISSUE THREAD

**Issue by mtpultz1977** [trivago/prettier-plugin-sort-imports#205]
**Your Environment**
 * **Prettier version**: 2.8.3
 * **node version**: 18.12.1
 * **package manager**: npm@8.19.2
 * **IDE**: VScode

**Describe the bug**

Updating from v3.4.0 to v4.0.0 in our AngularJS application started to move ngAnnotate 'ngInject'  statements to the top of files as if they were imports.

**To Reproduce**

This is an AngularJS function that I've altered to allow it to be used for reproduction.  Opening this in VSCode and saving any change in move all lines with `'ngInject';` to the top of the file with the imports.

```ts
import material from './material';
import textAngular from './textAngular';

export { material, textAngular };

export default function () {
  'ngInject';

  const $httpProvider = { interceptors: [] };

  $httpProvider.interceptors.push(($state, $rootScope) => {
    'ngInject';

    return {
      responseError(response) {
        if (response.status === 401) {
          $rootScope.notAuthorized = true;
          $state.go('dashboard', {}, { location: false });
        }
      },
    };
  });
}
```

Result after saving the file:

```ts
'ngInject';
'ngInject';

import material from './material';
import textAngular from './textAngular';

export { material, textAngular };

export default function () {
  const $httpProvider = { interceptors: [] };

  $httpProvider.interceptors.push(($state, $rootScope) => {
    return {
      responseError(response) {
        if (response.status === 401) {
          $rootScope.notAuthorized = true;
          $state.go('dashboard.notauthorized', {}, { location: false });
        }
      },
    };
  });
}

```

**Expected behaviour**

`'ngInject';` would not be moved since it isn't an import.

**Screenshots, code sample, etc**

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

In this particular part of the application import order has no rules due to it being legacy code.

```
{
  "singleQuote": true
}
```

**Error log**

No error it is purely a formatting issue.

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇

**Comment by c-dante** [comment]
Already have a PR open to fix this: https://github.com/trivago/prettier-plugin-sort-imports/pull/198
