### ISSUE TITLE
Do not call `yarn` directly in the package.json pre commands

### ISSUE THREAD

**Issue by matsko** [trivago/prettier-plugin-sort-imports#206]
**Your Environment**
 * **Prettier version**: 2.8.3
 * **node version** [12.x.x, 14.x.x]: 18.13
 * **package manager**: pnpm@7.26.3
 * **IDE**: VSCode

**Describe the bug**

When installed via `pnpm install`, pnpm expresses that the command fails due to `yarn` missing.

Install a fresh `nvm` version (like 18.13) and run `npm install -g pnpm`. Then create a new project add `@trivago/prettier-plugin-sort-imports` as a dep. Run install and see the error.

**Expected behavior**

Should work without the need to have a global `yarn` package manager.

**Comment by matsko** [comment]
Any ideas?

**Comment by matsko** [comment]
hello?

**Comment by ayusharma** [comment]
Please use require while loading the plugin if you use it pnpm. Something like this https://github.com/verdaccio/verdaccio/blob/c9bd22dcaa2f0d919338fb387ae261992f0e1116/prettier.config.js#L10

**Comment by ayusharma** [comment]
Feel free to reopen if you still face the issue.
