### ISSUE TITLE
'worklet' designation incorrectly formatted

### ISSUE THREAD

**Issue by ljukas** [trivago/prettier-plugin-sort-imports#209]
**Your Environment**
 * **Prettier version**: 2.8.4
 * **node version** 18.9:
 * **package manager**: yarn@2
 * **IDE**: vscode

**Describe the bug**

Using v4 of this package moves 'worklet' designation wrongly to the top of the file.

'worklet' is used in react-native-reanimated to show that that function should run on the UI thread instead of the JS thread. See example.

![image](https://user-images.githubusercontent.com/11976354/218964238-0574491c-e855-435b-b7ec-2704d1f2d775.png)

**To Reproduce**

Formatting using version 4 with the following config

![image](https://user-images.githubusercontent.com/11976354/218964344-d0286b62-6b55-414e-88b4-28d12f2704d1.png)

Moves 'worklet' designation away from the function and to the top of the file as an import wrongly in 50% of the cases. I dont know why it happens in certain cases.

Downgrading to 3.3.0 fixes this issue.

**Expected behavior**

I expect it to not move the 'worklet' designation at all.

**Error log**

No error logs can be linked since its not an error, it successfully formats it incorrectly.

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇

**Comment by ayusharma** [comment]
This is something new to me.  😄 It requires some investigation.

**Comment by c-dante** [comment]
Patched with https://github.com/trivago/prettier-plugin-sort-imports/pull/198

**Comment by ayusharma** [comment]
Thank you for the notification @c-dante.  I am closing this now.
