### ISSUE TITLE
Support // sort-imports-ignore

### ISSUE THREAD

**Issue by shalev-kaveh** [trivago/prettier-plugin-sort-imports#230]
**Is your feature request related to a problem?**
Yes, I can't ignore this plugin only on certain files.
To ignore import sort, we need to ignore it via `.prettierignore`, therefore ignoring prettifying the whole file.

**Describe the solution you'd like**

**Describe alternatives you've considered**
I suggest a simple fixup, similar to other sort imports plugins provide:
https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/d5ac2f4f2dba549a5a55bf05b3f2f0360e2358e4/index.js#L14

Files containing the substring `// sort-imports-ignore` or `// tslint:disable:sort-imports` will be skipped.

So files with the `sort imports ignore` comment won't be reordered, e.g.

```ts
// sort-imports-ignore
import './polyfills';

import foo from 'foo'
```

**Additional context**
A follow-up on: https://github.com/trivago/prettier-plugin-sort-imports/issues/26 due to the large demand by the community

**Comment by ElForastero** [comment]
I would like to provide an additional use case for such a rule. I have a singleton configuration object that needs to be imported on the very first line.

```ts
// This import MUST be placed before any other app code
import './config';
import { registerRootComponent } from 'expo';
import App from './App';

// registerRootComponent calls AppRegistry.registerComponent('main', () => App);
// It also ensures that whether you load the app in Expo Go or in a native build,
// the environment is set up appropriately
registerRootComponent(App);
```

**Comment by kiliman** [comment]
You can configure the sorting rules, so if you want, you can have the local imports first. Perhaps add a prefix to ensure those are always first, like `'./!setup-env-vars.ts'`
```js
// sort ./!* files first, then normal modules, followed by local files
importOrder: ['^[.]\\/!', '<THIRD_PARTY_MODULES>', '^[.]\\/'],
```

Although I prefer to avoid relying on side-effects, at least with this naming convention, it will signal to the developer that this is a special file.

<img width="812" alt="image" src="https://github.com/epicweb-dev/epic-stack/assets/47168/dc0e1f94-7dbc-4223-8b9b-f9a34efdb374">

**Comment by bdombro** [comment]
I would love to see an ignore rule. The suggested solution, sorting relative first, is absolutely not what I want.

**Comment by kiliman** [comment]
Look, I was just trying to offer a workaround since the plugin doesn't currently support this use case. Not sure why I got the downvotes. I never said we don't need this.

**Comment by shalev-kaveh** [comment]
Resolved at https://github.com/trivago/prettier-plugin-sort-imports/pull/237
Thanks!

**Comment by bdombro** [comment]
No new release yet though... :-/

**Comment by byara** [comment]
Released in [v4.3.0](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v4.3.0)

**Comment by bdombro** [comment]
TY!

**Comment by volosovich** [comment]
TY
