### ISSUE TITLE
Sorting doesn't work when pnpm is used as package manager

### ISSUE THREAD

**Issue by esjs** [trivago/prettier-plugin-sort-imports#234]
**Your Environment**
 * **Prettier version**: 2.8.8
 * **node version** [18.16.0]:
 * **package manager**: [pnpm@8.5.1]
 * **IDE**: [VScode]

**Describe the bug**

Sorting doesn't work when `pnpm` is used as package manager, but everything works as expected when `yarn@1.22.19` is used as package manager.

**To Reproduce**

1) Init new npm package with following configuration
```json
{
  "name": "prettier-format-test",
  "version": "1.0.0",
  "main": "index.js",
  "devDependencies": {
    "@trivago/prettier-plugin-sort-imports": "4.1.1",
    "prettier": "2.8.8"
  }
}

```

2) Add .prettierrc config
```json
{
  "singleQuote": true,
  "importOrder": ["^node:", "^\\w", "^[./]"],
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true
}
```

3) Create index.js with following content
```js
import { Cipher } from 'crypto';

import { accessSync } from 'node:fs';

```

4) Save file

**Expected behavior**

Imports should be formatted after save and content of the file should become
```js
import { accessSync } from 'node:fs';

import { Cipher } from 'crypto';

```

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇

**Comment by eyerrock** [comment]
I was having the same issue while using the same versions as mentioned and found a solution.
Adding `"plugins": ["@trivago/prettier-plugin-sort-imports"]` to the `.prettierrc` file fixed it:
```json
{
  "singleQuote": true,
  "importOrder": ["^node:", "^\\w", "^[./]"],
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true,
  "plugins": ["@trivago/prettier-plugin-sort-imports"]
}
```

**Comment by esjs** [comment]
Works like a charm, 
Thank you so much @eyerrock.

I think that it should be added to readme.md, but I'd better create a new issue for this one.
