### ISSUE TITLE
Support for prettier 3

### ISSUE THREAD

**Issue by Ericlm** [trivago/prettier-plugin-sort-imports#240]
**Is your feature request related to a problem?**
Prettier has just been updated to version 3.0.0 (see [the changelog](https://prettier.io/blog/2023/07/05/3.0.0.html)) ; however, this package only supports prettier up to `2.x.y`.

**Describe the solution you'd like**
It would be great if this plugin could work with versions > prettier 3.0.0

**Describe alternatives you've considered**
So far, I stay on version `2.8.8`

**Comment by basselworkforce** [comment]
PR submitted: https://github.com/trivago/prettier-plugin-sort-imports/pull/239

**Comment by basselworkforce** [comment]
This PR now merged as v4.2.0, please note during my testing I found that I now had to add the plugin to the config with `npm` (when I never had to before) as per: 
```
module.exports = {
    ...
    "plugins": ["@trivago/prettier-plugin-sort-imports"]
}
```
https://github.com/trivago/prettier-plugin-sort-imports#usage

**Comment by gentle-noah** [comment]
@basselworkforce - which config file specifically?

**Comment by clintonb** [comment]
prettierrc: https://prettier.io/docs/en/plugins.html

**Comment by kellengreen** [comment]
Confirmed working, thanks everyone.
