### ISSUE TITLE
Prettier v3 throws warning "Ignored unknown option" for `importOrder` / `importOrderSeparation`

### ISSUE THREAD

**Issue by escapedcat** [trivago/prettier-plugin-sort-imports#244]
**Your Environment**
 * **Prettier version**: 3.0.0
 * **node version**: 18.8.0
 * **package manager**: yarn@1.22.19
 * **IDE**: CLI

**Describe the bug**

After updating to prettier v3 it throws warnings.

**To Reproduce**

Install latest version of `prettier-plugin-sort-imports` and prettier v3

**Expected behavior**

No warning is thrown and plugin works as expected.

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

`.prettierrc`
```json
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "importOrder": ["^[./]"],
  "importOrderSeparation": true
}
```

**Error log**

```sh
Checking formatting...
[warn] Ignored unknown option { importOrder: ["^[./]"] }.
[warn] Ignored unknown option { importOrderSeparation: true }.
...
```

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇 

_I am but would need support_

**Comment by escapedcat** [comment]
Switching from `.prettierrc` to `.prettierrc.js` like suggested in https://github.com/trivago/prettier-plugin-sort-imports/issues/131#issuecomment-1163488213 works for me.  
Closing this :P

**Comment by Hypenate** [comment]
This is bad... 
Can you alteast mention that this plugin does not work with .prettierrc?

Lost a lot of time because of this. We removed the plugin.

**Comment by ollebergkvist** [comment]
@escapedcat This is not a fix if you use ESM unfortunately

**Comment by teddythinh** [comment]
My `.prettierrc` file works after adding `"plugins": ["@trivago/prettier-plugin-sort-imports"]`

```json
{
  "importOrder": ["^@core/(.*)$", "^@server/(.*)$", "^@ui/(.*)$", "^[./]"],
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true,
  "plugins": ["@trivago/prettier-plugin-sort-imports"]
}
```

I'm using:

- `"@trivago/prettier-plugin-sort-imports": "^5.2.0"` 
- `"prettier": "^3.1.1"`
- `"typescript": "^5"`
- `"react": "^18"`
- `"next": "14.2.7"`

Hope this helps! 😄

**Comment by tofrankie** [comment]
> [@escapedcat](https://github.com/escapedcat) Just arrived to this thread. This is not a fix if you use ESM unfortunately :/

Can you explain why?
