### ISSUE TITLE
Prettier > 3 doesn't work

### ISSUE THREAD

**Issue by mike667** [trivago/prettier-plugin-sort-imports#245]
Hello maintainers, thank you for amazing package. Could you help me with my issue?

**Your Environment**
 * **Prettier version**: **2.8.8** or **3.0.0**
 * **node version** [20.3.0]:
 * **package manager**: [npm@9.8.1]
 * **IDE**: [Pycharm]

**Describe the bug**
Sort doesn't work with prettier 3.0.0.

I use latest version. "@trivago/prettier-plugin-sort-imports": "**^4.2.0**". When I update prettier to version **3.0.0** sorting silently stop working, after rollback to v**2.8.8** everything works as expected.

My .prettierrc
```
{
    "importOrder": [
        "^(common|components)(.*)$",
        "^data-service(.*)$",
        "^(hooks|utils|context)(.*)$",
        "^(constants|themes|route-urls)(.*)$",
        "^../(.*)$",
        "^./(.*)$"
     ],
    "importOrderSeparation": true,
    "importOrderSortSpecifiers": true
}
```

**Comment by timgcarlson** [comment]
I'm also encourting this issue with prettier 3.0.0. To resolve I had to downgrade back to 2.8.8, and also had to downgrade [eslint-plugin-prettier](https://www.npmjs.com/package/eslint-plugin-prettier) to 4.2.1 (from 5.0.0).

**Comment by Rhym** [comment]
I migrated to https://github.com/IanVS/prettier-plugin-sort-imports, and it has been great.

**Comment by sascha-kaleidoscode** [comment]
I only added

```plugins: ['@trivago/prettier-plugin-sort-imports']```

to my configuration and it works just fine.

-----
If you are using VS Code you may need to restart the ESLint Server
- open the command palette
- search for `eslint restart` and execute
- wait a few seconds and you should be good to go

**Comment by pallymore** [comment]
Hi looks like we just need to specify this plugin in the prettierrc file. 

```ts
// .prettierrc
plugins: ['@trivago/prettier-plugin-sort-imports']
```

**Comment by FrancescoSaverioZuppichini** [comment]
what is prettierrc? I have prettier.config and If I run prettier --write app  the imports do not get sorted - thanks a lot

**Comment by pallymore** [comment]
> what is prettierrc? I have prettier.config and If I run prettier --write app the imports do not get sorted - thanks a lot

https://prettier.io/docs/en/configuration.html 

yep sorry it should be the prettier config file (we picked the filename `.prettierrc` ) - it works fine for us once we added this to the `plugins` field.

**Comment by smenshikov** [comment]
Probably this trick about `plugins: ['@trivago/prettier-plugin-sort-imports']` should be described in README until the problem is solved

**Comment by mike667** [comment]
Thank you @pallymore

**Comment by FrancescoSaverioZuppichini** [comment]
> > what is prettierrc? I have prettier.config and If I run prettier --write app the imports do not get sorted - thanks a lot
> 
> https://prettier.io/docs/en/configuration.html
> 
> yep sorry it should be the prettier config file (we picked the filename `.prettierrc` ) - it works fine for us once we added this to the `plugins` field.

I apologies, I am a noob here - could you give me a little more context or just a couple of steps I need to do 😃

**Comment by austinschrader** [comment]
This worked for me as well, with a tweak. I created a .prettierrc in the root of my nextjs app, and it now looks like below. 

Note: .prettierrc written in JSON
.prettierrc
```
{
    "singleQuote": true,
    "importOrder": [
        "<THIRD_PARTY_MODULES>",
        "^@internal/(.*)$",
        "^[./].*(?<!\\.(c|le|sc)ss)$",
        "^[.]/[-a-zA-Z0-9_]+[.](module)[.](css|scss|less)$"
    ],
    "importOrderSeparation": true,
    "importOrderSortSpecifiers": true,
    "printWidth": 120,
    "plugins": [
        "@trivago/prettier-plugin-sort-imports"
    ]
}
```

**Comment by eagleeyejack** [comment]
Might be late to the party with this one, but just restarting my IDE did the trick, classic 😅

**Comment by zcmgyu** [comment]
I got this error:

> `[error] Cannot find package '@trivago/prettier-plugin-sort-imports' imported from /Users/project/noop.js`

In my `prettier.config.js`, I had:
```js
plugins: ["@trivago/prettier-plugin-sort-imports"]
```

I tried several recommended fixes:
- Restarting the ESLint server
- Switching to `.prettierrc` instead of `prettier.config.js`

But none of those worked.

**Environment:**
- `"prettier": "^3.6.2"`
- `"@trivago/prettier-plugin-sort-imports": "^5.2.2"`

**What finally worked was changing the config to:**
```js
plugins: [require.resolve("@trivago/prettier-plugin-sort-imports")]
```

**That resolved the error, and the plugin loaded correctly.**

For others facing the same issue, this might save you some time!
