### ISSUE TITLE
Unnecessary removal of `$$()` when using Vue Reactivity Transform macros

### ISSUE THREAD

**Issue by AnotiaWang** [trivago/prettier-plugin-sort-imports#247]
**Your Environment**
 * **Prettier version**: 3.0.1
 * **node version**: 20.3.0
 * **package manager**: pnpm@8
 * **IDE**: VS Code

**Describe the bug**

I'm using Vue with the [Reactivity Transform macros](https://vue-macros.sxzz.moe/features/reactivity-transform.html). There's a `$$()` macro to keep reactivity of refs when passing them to functions. However this plugin always tries to rename `$$()` to `$()`, which leads to Vue throwing an error `$ can only be used as the initializer of a variable declaration`.

**To Reproduce**

1. Create a Vue 3 project. Please install the Reactivity Transform macros if you're using Vue 3.3+, or [enable it in config](https://vuejs.org/guide/extras/reactivity-transform.html) if using Vue 3.2+.
2. Write a component, and use it in another component. Specify a `ref` for the component.
```vue
<template>
  <some-component ref="componentRef" />
</template>

<script setup lang="ts">
import { provide } from 'vue'
import SomeComponent from '../path/to/component.vue'

const componentRef = $ref<InstanceType<typeof SomeComponent>>()

provide('any-key', $$(componentRef))
</script>
```
3. Save the file. `$$(componentRef)` is changed to `$(componentRef)`.
4. Run the project

**Expected behavior**

The `$$()` macros shouldn't be changed.

**Screenshots, code sample, etc**

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**
.prettierrc.json
```json
{
  "arrowParens": "avoid",
  "semi": false,
  "singleQuote": true,
  "trailingComma": "all",
  "printWidth": 100,
  "plugins": ["@trivago/prettier-plugin-sort-imports"],
  "importOrder": ["^@/(.*)$", "^[./]"],
  "importOrderSeparation": true,
  "importOrderSortSpecifiers": true
}

```

**Error log**

`[plugin:commonjs] $ can only be used as the initializer of a variable declaration`

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇

**Comment by adamDilger** [comment]
I think this issue https://github.com/trivago/prettier-plugin-sort-imports/issues/276 is related, it's due to the `$$` being a special replacement group in a call to `"".replace()`, which this plugin uses in pre-processing vue code.

I've submitted a fix PR which should address this issue

**Comment by byara** [comment]
This should be addressed in the [v5](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v5.0.0). Please feel free to reopen in there is an issue.
