### ISSUE TITLE
Throws when babel config has override section

### ISSUE THREAD

**Issue by aliaksandr-yermalayeu** [trivago/prettier-plugin-sort-imports#25]
The problem occurs when using the plugin with more complex babel configuration. Example:
```js
{
     overrides: [{
         test: /\.jsx$/,
         presets: ['@babel/preset-react']
     }]
}
```
This is not specified anywhere in Babel documentation, but Babel expects that the `filename` option should be provided, when calling `loadPartialConfig()` or `loadOptions()`.

Otherwise this [line](https://github.com/trivago/prettier-plugin-sort-imports/blob/master/src/preprocessor.ts#L17) causes the exception:
`Error: Configuration contains string/RegExp pattern, but no filename was passed to Babel`

I suggest at least to wrap it with try-catch block and use base config as a fallback.

**Comment by ythecombinator** [comment]
Any plans to address this?

**Comment by ythecombinator** [comment]
Any plans to address this?

**Comment by byara** [comment]
Hopefully, this will be fixed in the next release soon.

**Comment by byara** [comment]
With the release of [v2.0.1](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v2.0.1), this should be fixed. 
This version should not depend on `.babelrc` anymore

If there was still problems, you can of course re-open this issue.
