### ISSUE TITLE
Support // prettier-ignore 

### ISSUE THREAD

**Issue by levenleven** [trivago/prettier-plugin-sort-imports#26]
Is it possible to support `// prettier-ignore` comment? So marked import won't be reordered, e.g.

```javascript
// prettier-ignore
import './polyfills';

import foo from 'foo'
```

**Comment by tomspeak** [comment]
+1 — Just came to the project to open a discussion about this feature.

**Comment by ayusharma** [comment]
Thanks for the suggestions.  I'll look into the possibility of implementing it.

**Comment by Beraliv** [comment]
Let me know if anyone is working at this at the moment

I don't have an experience in Prettier so it takes more time for me

**Comment by ayusharma** [comment]
We do not know where to put the import with `// prettier-ignore`. Let's imagine the situation:

```
import x from 'x';
// prettier-ignore
import y from 'y';
import z from 'z';
```

Now where to put this ignored import? I don't think that this feature will make the majority of our users happy.  Please feel free to open the issue for further discussion.

**Comment by nmay231** [comment]
@ayusharma How about support for `prettier-ignore-start/-end`?

```js
import 'lib4';
import 'lib2';
// prettier-ignore-start
import 'lib6';
import 'lib1';
// prettier-ignore-end
import 'lib5';
import 'lib3';
```

Becomes

```js
import 'lib2';
import 'lib4';
// prettier-ignore-start
import 'lib6';
import 'lib1';
// prettier-ignore-end
import 'lib3';
import 'lib5';
```

In essence, blocks of imports before and after the comment get sorted in their own separate groups; notice how lib4 stays in the top group and lib3 stays in the bottom.

**Comment by DaddyWarbucks** [comment]
I would like to see this feature as well. I am currently handling this with `.prettierignore`, buts its a bummer to disable all prettier functions in the file. Even simpler than the solution mentioned above, I would be happy with an ignore comment to just ignore sorting that whole file.

**Comment by adroste** [comment]
Needs to be reopened @ayusharma .

**Comment by ArturBaybulatov** [comment]
Please, reopen the issue

**Comment by franciscohanna92** [comment]
This issue should be reopened. Merging #111 would solve most use cases

**Comment by shalev-kaveh** [comment]
+1

**Comment by nandastone** [comment]
+1

**Comment by RIP21** [comment]
This has to be reopened. It's an absolutely VALID concern and feature. For instance, some of the jest/vitest mocks may be sensitive to the order of the imports and this plugin simply forces you to COMPLETELY ignore the file as otherwise the test fails after reordering.

**Comment by ya-erm** [comment]
Looks like it solved in https://github.com/trivago/prettier-plugin-sort-imports/issues/230
