### ISSUE TITLE
SyntaxError: Unexpected token throws when using with flow

### ISSUE THREAD

**Issue by javaharut** [trivago/prettier-plugin-sort-imports#27]
I tried to add on react project which uses flow but it shows several errors on nullable types such as 

`handleChange = (value: ?string) => {}`

or when have such code during import

`import { type Something } from './__generated__/;`

**Comment by byara** [comment]
With the release of [v2.0.1](https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v2.0.1), this should be fixed. 
Either prettier will figure out the syntax correctly, or you can use `experimentalBabelParserPluginsList` to pass the correct parser name (in your case `flow`).

If there was still problems, you can of course re-open this issue.
