### ISSUE TITLE
Use project babel config when available

### ISSUE THREAD

**Issue by gavinhenderson** [trivago/prettier-plugin-sort-imports#3]
In our project we have a pretty complex babel setup. It would be nice if this plugin parsed our code with our babel setup rather than a pre determined setup.

Some files in our project cannot be parsed by the config that is hard coded as:
```
 const ast = parser(code, {
        sourceType: 'module',
        plugins: ['typescript', 'jsx'],
});
```

This causes prettier to throw an error, which blocks our CI pipe, so for the time being we have had to remove this plugin

**Comment by gavinhenderson** [comment]
Happy to submit a pr for this, just want to make sure it's something you would be interested in adding

**Comment by ayusharma** [comment]
@gavinhenderson Sorry for the late reply. I was on vacation. Please feel free to PR this.

**Comment by gavinhenderson** [comment]
@ayusharma Thanks for merging!

Is there any chance you could publish a new version to NPM so we can use the changes?

**Comment by ayusharma** [comment]
Released in https://github.com/trivago/prettier-plugin-sort-imports/releases/tag/v1.2.0. Please let me know if there is an issue.
