### ISSUE TITLE
Install fails with `sh: patch-package: command not found`

### ISSUE THREAD

**Issue by bramstein** [trivago/prettier-plugin-sort-imports#321]
**Your Environment**
 * **node version**: [20.x]
 * **package manager**: [npm@10]

**Describe the bug**

When installing the package using `npm install @trivago/prettier-plugin-sort-imports` the install fails with:

```
npm error code 127
npm error path ./node_modules/@trivago/prettier-plugin-sort-imports
npm error command failed
npm error command sh -c patch-package
npm error sh: patch-package: command not found
```

Seems to be related to a change in #310.

**Comment by byara** [comment]
This should not happen anymore after the patch. Please feel free to reopen if it happens still.
