### ISSUE TITLE
Prettier-plugin-sort-imports removes generic types for prettier v3.3.3+

### ISSUE THREAD

**Issue by LinusPhoenix** [trivago/prettier-plugin-sort-imports#340]
**Your Environment**
 * **Prettier version**: 3.3.3 and higher
 * **node version**: 20.9.0
 * **package manager**: npm 10.1.0
 * **IDE**: CLI

**Describe the bug**

Prettier removes generic arguments from type like `Promise`. Consider this short snippet:

```Typescript
export async function test(): Promise<void> {
  console.log("test!");
}
```

Prettier changes it to:

```Typescript
export async function test(): Promise {
  console.log("test!");
}
```

After which typescript shows an error: `Generic type 'Promise<T>' requires 1 type argument(s).ts(2314)`

**To Reproduce**

Create a new typescript project:

```bash
npm i --save-dev --save-exact typescript@5.2.0 @types/node@20.14.8 prettier@3.3.3 @trivago/prettier-plugin-sort-imports@5.2.0
```

Add `.prettierrc.js`:
```javascript
module.exports = {
    plugins: ["@trivago/prettier-plugin-sort-imports"],
};
```

Save the example snippet above in a file. Run prettier.

**Expected behavior**

The code snippet should not be reformatted at all. Prettier checks should pass.

**Screenshots, code sample, etc**

**Configuration File (cat .prettierrc, prettier.config.js, .prettier.js)**

**Error log**

**Contribute to @trivago/prettier-plugin-sort-imports**

- [ ] I'm willing to fix this bug 🥇

**Comment by LinusPhoenix** [comment]
My mistake, I was using an outdated prettier version on the CLI by accident.

**Comment by alpharaoh** [comment]
How did you fix this sorry? All the generic types in my files keep disappearing when I save. My project is running the latest prettier `^3.4.2`

**Comment by solastley** [comment]
+1 this is happening to us as well on 3.4.2
