### ISSUE TITLE
Add import groups configuration

### ISSUE THREAD

**Issue by bastienrobert** [trivago/prettier-plugin-sort-imports#36]
## Summary

My actual use-case is that I want React to be imported as first but I also want line breaking between my imports. If in the `importOrder` configuration I setup the following : `"importOrder": ["^react", "^(?!react)\\w+$"]` (from https://github.com/trivago/prettier-plugin-sort-imports/issues/7#issuecomment-739413024) with `importOrderSeparation: true`, it will add a line break between my imports from `node_modules`.

## Actual behavior
```ts
import React from 'react'

import classnames from 'classnames'
```

## Expected behavior
```ts
import React from 'react'
import classnames from 'classnames'
```

For the moment, if you want to `importOrderSeparation`, there is no way of configuring import groups. I think it could be awesome if we could specify in the configuration where is the line breaking.

## Possible solution

Create a configuration like:

```json
{
  "importOrder": [
    // no line breaking if specified in a sub-array
    ["^react", "^(?!react)\\w+$"],
    "^[./]"
  ]
}
```

We could event remove the `importOrderSeparation` option because this way will allow you to put everything in the same block:

```json
{
  "importOrder": [
    // no line breaking if specified in a sub-array
     [
       "^react", 
       "^(?!react)\\w+$", 
       "^[./]"
     ]
  ]
}
```

I'll be glad to PR this ;) 

Related to #1 & #7

**Comment by atombrenner** [comment]
I like the idea of a nested array for configuring groups. Unfortunately, prettier does not allow this type of option. Only int, boolean, choice and path are allowed. `importOrder` is of type array of path (=string), an array of arrays would lead to an invalid prettier configuration.

**Comment by atombrenner** [comment]
I added PR #42 as implementation

**Comment by atombrenner** [comment]
Hi @ayusharma did you have time to look into my PR? Totally OK if you don't like it, just a little feedback would be nice, if there is any chance that you could look into it. :-)

**Comment by ayusharma** [comment]
Closing the issue in favor of #42

**Comment by nomoon** [comment]
I see that #42 was closed. This is a shame. This is currently one of the only widely-available and actively maintained import sorting packages, but its inability to let people configure it in a few more ways (such as being able to decide what patterns are grouped together and which are separated) makes it far less usable in projects which have an established convention.

**Comment by byara** [comment]
I have re-open #42 due to the fact that it can help a lot of people and solve lot's of issues. Let's work on it and improve the PR.
