### ISSUE TITLE
Remove unused imports

### ISSUE THREAD

**Issue by Southclaws** [trivago/prettier-plugin-sort-imports#46]
Love this plugin! Saves so much time.

One thing I'd love it to do is remove imports that aren't used. VS Code does this already with alt+shift+O but the ability for this plugin to do it alongside the sorting would be great.

**Comment by byara** [comment]
Hi, I believe ESLint already does this. You can use this plugin for that: https://www.npmjs.com/package/eslint-plugin-unused-imports

**Comment by louisgv** [comment]
The esilnt plugin doesn't work well for project that use prettier as the primary code formatter however. Esilnt as a code formatting tool is very slow and chunky. It's great for linting the entire project and auto-fix in a batchjob, but for code editing and CTRL+S however, it takes ~5s to run (bc it does try to scan and attempt to fix a bunch of other stuffs that's unrelated)

It would be awesome if we can have the same behavior as https://github.com/simonhaenisch/prettier-plugin-organize-imports but coupled with regex sorting (which is super powerful)

**Comment by louisgv** [comment]
I investigated how prettier-plugin-organize-imports invoked the ts's language service. It's pretty simple:

https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/dd6cf593a86bb1ab336fed1deaf30773c1535e96/lib/organize.js#L12-L17

I think it would be nice to pre-process with the above prior to actual sorting:
https://github.com/trivago/prettier-plugin-sort-imports/blob/5462a12e748838c22199798d1fb1b09ca912db8a/src/preprocessor.ts#L42

**Comment by vadimdemedes** [comment]
Is it possible to turn this off and leave unused imports in the source code? I didn't expect that a sorting Prettier plugin would remove code.

**Comment by regalstreak** [comment]
@vadimdemedes yes, by enabling `organizeImportsSkipDestructiveCodeActions` in `prettier-plugin-organize-imports`

**Comment by iulspop** [comment]
Is anyone working on this? I prefer to run this with Prettier when I format on save, rather than configuring eslint to fix it when I commit or to manually run the VS Code organize imports or delete unused imports command.

Considering switching to https://github.com/simonhaenisch/prettier-plugin-organize-imports but I quite like having some control over the import order/groups.

**Comment by remi-blaise** [comment]
I would love this also!
Switching to https://github.com/simonhaenisch/prettier-plugin-organize-imports for now because this feature is missing, even if I like sorting with regexes more

**Comment by lnuvy** [comment]
I have also using monorepo by relying solely on oxc and Prettier. (removing the heavy ESLint configuration)

`prettier-plugin-organize-imports` package lacks certain functionalities, and since we prefer not to use ESLint, it would be beneficial to have these options integrated directly 🥹🥹
