### ISSUE TITLE
Parser babel-flow not sorting imports

### ISSUE THREAD

**Issue by wityan** [trivago/prettier-plugin-sort-imports#47]
Hei
(Its the same issue as in https://github.com/trivago/prettier-plugin-sort-imports/issues/6)

I have just tested this in the current Version and I think it is not working any longer. I have created a Repository to demonstrate it, here the link https://github.com/wityan/prettier-import-example-error.

In src/index.jsx the common import should come before the test import.

Is there an error in my config or is something not working anymore?

**Comment by byara** [comment]
Hey @wityan , thanks for reporting this. We still support flow but you only have to use `flow` in your `.prettierrc` file.
Hope this helps.

**Comment by wityan** [comment]
@byara so you mean by using experimentalBabelParserPluginsList: ["flow"] ?

**Comment by byara** [comment]
Not really, just the following in your rc file:
```json
{
  "parser": "flow",
  "printWidth": 80,
  "tabWidth": 4,
  "trailingComma": "all",
  "singleQuote": true,
  "jsxBracketSameLine": true,
  "semi": true,
  "importOrder": ["^common/(.*)$", "^test/(.*)$"],
  "importOrderSeparation": true
}
```

**Comment by wityan** [comment]
Works!
Thnkas @byara
