### ISSUE TITLE
Ignore blocks for Angular Universal

### ISSUE THREAD

**Issue by rkorebrits** [trivago/prettier-plugin-sort-imports#48]
Hi there, first of all, many thanks for the plugin! And especially recent the fix that allows us to run in TS/Angular.

We have an instance that runs pre-rendering with Angular Universal, and in our `server.ts` file, we need to instantiate a browser emulator, before `import { AppServerModule }` (see code below). Running your plugin however puts all of the imports at the top, which breaks our pre-rendering of our app.

I have looked at the standard [Prettier ignore](https://prettier.io/docs/en/ignore.html#ignoring-files-prettierignore), which doesn't seem to allow ignoring blocks (`range ignore`) in JavaScript code.

Is there a smart way to ignore a file/block from import sorting that works with your plugin? 

Thanks!

```
...

// Emulate browser APIs
const domino = require('domino');
const templateA = readFileSync(join(distFolder, indexHtml)).toString();

const win = domino.createWindow(templateA);
win.Object = Object;
win.Math = Math;
// NOTE: This must happen before importing `AppServerModule`
global['window'] = win;
global['document'] = win.document;

import { AppServerModule } from './src/projects/website';

...
```

**Comment by byara** [comment]
Thanks for reporting this, basically what we do in the plugin is a preprocessing, then we pass the code to prettier. Therefore, any block / ignore comment should be implemented in the plugin itself. We will look into it but it might take some time but hey, any PR is welcome 👍

**Comment by rkorebrits** [comment]
Thanks! Unfortunately not able to submit a PR :-( For now we have excluded the whole file in `.prettierignore`, which is fine for us

**Comment by ayusharma** [comment]
Hi @rkorebrits , The plugin is a pre-processor and does not have any information about the file meta including the name. We just get the source and process it. The requested functionality is out of the scope of the plugin.
