### ISSUE TITLE
Not sorting imports in .vue files

### ISSUE THREAD

**Issue by fbjorn** [trivago/prettier-plugin-sort-imports#49]
Hi, I have a following config:

```json
{
  "importOrder": [
    "^vue/(.*)$",
    "^[^@v](.*)$",
    "^@(.*)$",
    "^[./]"
  ],
  "importOrderSeparation": true,
}

```

And an `App.vue` file (already formatted with prettier):

```vue
<script>
import Vue from 'vue'
import TheNavBar from '@/components/TheNavBar'
import dayjs from 'dayjs'
</script>
```

When I copy its content to `.ts` file, it gets formatted as expected:
```typescript
import Vue from 'vue'

import dayjs from 'dayjs'

import TheNavBar from '@/components/TheNavBar'

```

Is it possible to somehow enable `.vue` files support?

**Comment by byara** [comment]
Hey @fbjorn thanks for reporting this. Could you please provide a sample repo, it surely makes investigating this easier.

**Comment by fbjorn** [comment]
@byara sure, I created a repo: https://github.com/fbjorn/vue-prettier-plugin-sort-imports-example

It's bare minimal, but demonstrates that plugins sorts `.ts` file correctly, but does nothing for a `.vue`

**Comment by ayusharma** [comment]
Hi, We do not support the vue as of now. It is in our roadmap for version 4.

**Comment by muety** [comment]
I'm looking forward to Vue support! :rocket:

**Comment by blake-newman** [comment]
I've added the base support for `.vue` files; i've successfully applied the patch via `yarn patch` and working successfully in a large project.
