### ISSUE TITLE
Feature request: Preserve comments

### ISSUE THREAD

**Issue by Jyrno42** [trivago/prettier-plugin-sort-imports#5]
It would be lovely if it comments inside the imports could be preseved. This becomes a problem with long imports when only a single item is imported (and there is an eslint rule about max-line-length in place). 

For example:

```
// eslint-disable-next-line max-len
import { UpdateCheckoutShippingAddress_checkoutEmailUpdate_checkoutErrors as CheckoutError } from '@api-sdk/mutations/types/UpdateCheckoutShippingAddress';

import BusinessForm, { BusinessFormValues } from './Forms/BusinessForm';
import ProfileForm, { ProfileFormValues } from './Forms/ProfileForm';
```

currently always becomes this:

```
import { UpdateCheckoutShippingAddress_checkoutEmailUpdate_checkoutErrors as CheckoutError } from '@saleor-sdk/mutations/types/UpdateCheckoutShippingAddress';

import BusinessForm, { BusinessFormValues } from './Forms/BusinessForm';
import ProfileForm, { ProfileFormValues } from './Forms/ProfileForm';

// eslint-disable-next-line max-len
```

**Comment by ayusharma** [comment]
Hi @Jyrno42, Thanks for opening the ticket. Ideally, it should not be the case, I verified and I could not reproduce it. Is this a `.js` file or a `.ts` file ?

**Comment by Jyrno42** [comment]
It is a TS file and the item being imported is a type. I'll try to set up a working repro tomorrow.

**Comment by Retsam** [comment]
Trying to use this plugin myself, and it appears to be losing all the comments in the files, which causes the formatting to fail, due to some of the prettier validation.

**Comment by vamcs** [comment]
Same for me as above, the formatting fails completely because my component has comments outside the scope of the function.

```
["ERROR" - 11:06:15] Error formatting document.
["ERROR" - 11:06:15] Comment "*content of the comment*." was not printed. Please report this error!
```

**Comment by byara** [comment]
FYI @ayusharma, I think @Jyrno42 is right. I tried this on a bigger code base and the same behavior described on the issue happens. Comments are kept in correct place only if they are placed on top, otherwise they are left at the bottom of the import section.

**Comment by ayusharma** [comment]
Just a note here: We are working on the issue and found a really nice solution to solve the problem.

**Comment by byara** [comment]
Hey I closed the issue because we have now a pre-release. You can install this version and see if it fixes the issue.

`yarn add -D @trivago/prettier-plugin-sort-imports@pre-release`

Anyway, we are going to release a stable version soon.
