### ISSUE TITLE
Material UI Theme Object raising unsolvable error

### ISSUE THREAD

**Issue by RohitRajP** [trivago/prettier-plugin-sort-imports#50]
When using MaterialUI in a react application, we can set custom theme object in this way:
```ts
import { Theme } from '@material-ui/core';
const commonMUITheme = <Theme>{
    typography: {
        fontFamily: 'Inter',
    },
};
```

However, on adding [@trivago/prettier-plugin-sort-import](https://github.com/trivago/prettier-plugin-sort-imports) to the project, the following error occurs:

![image](https://user-images.githubusercontent.com/44432182/115979031-255b7300-a5a1-11eb-9e99-5bab04ce3cea.png)

We have tried searching for a similar error in the issues or tweaking the `experimentalBabelParserPluginsList` configuration to no avail. 

Other than this one specific problem with the `Theme` object from MaterialUI, there are no issues with explicit typecasting.

Is this a problem with the MaterialUI `Theme` type, because no error is being thrown without this plugin activated.

**Comment by byara** [comment]
Thanks for reporting this @RohitRajP 
It could be. But to be able to investigate this, a sample repo would help a lot!
