### ISSUE TITLE
Plugin is not loaded when using pnpm

### ISSUE THREAD

**Issue by brattonross** [trivago/prettier-plugin-sort-imports#51]
First, thanks for your hard work on this plugin!

When installing dependencies using pnpm and then running prettier I get the warning: `Ignored unknown option { importOrder: [...] }`.

If I remove node_modules, install dependencies with npm, and then run prettier, the files are formatted as expected.

**Comment by byara** [comment]
Hey @brattonross thanks for reporting this. That is true, we did not test the setup with pnpm. Could you maybe send a PR to fix that issue?

**Comment by ayusharma** [comment]
This is a valid issue. I also tried to integrate the plugin in the https://github.com/verdaccio/verdaccio. I could not manage it. We'll keep you updated if there is a solution.

**Comment by ayusharma** [comment]
The reason is that the prettier plugins are picked automatically from the node_modules and the pnpm has a different architecture.  I think this issue is out of scope of this plugin and requires discussion in the prettier project.

**Comment by brattonross** [comment]
Thank you for taking a look at the issue! I agree that it sounds like it is out of scope for this plugin.

The [prettier docs](https://prettier.io/docs/en/plugins.html) seem to suggest that you can manually specify plugins / directories to search for plugins, and although I haven't tried it myself I imagine that this could be a workaround for pnpm users.

**Comment by nirtamir2** [comment]
@brattonross did you find a workaround that works for you?

**Comment by raDiesle** [comment]
Is there a way I can fix it when using package.json, where no require.resolve is available ?

**Comment by shanu-mol** [comment]
> Inspired by [simonhaenisch/prettier-plugin-organize-imports#34 (comment)](https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/34#issuecomment-934676163) I solved it by adding to `.prettierrc.js`:
> 
> ```js
> module.exports = {
>   plugins: [
>     require.resolve("@trivago/prettier-plugin-sort-imports"),
>   ],
> };
> ```

This will also work with .prettierrc.json
```json
{
 "plugins": ["@trivago/prettier-plugin-sort-imports"]
}
```

**Comment by acelaya** [comment]
> For all, Who are using typescript. This will also work with .prettierrc.json
> 
> ```json
> {
>  "plugins": ["@trivago/prettier-plugin-sort-imports"]
> }
> ```

I can confirm this also works if the config is defined in package.json

**Comment by qiutian00** [comment]
```js
{
 "plugins": ["@trivago/prettier-plugin-sort-imports"]
}
```
It works ha ha.
