### ISSUE TITLE
Commented imports dupe

### ISSUE THREAD

**Issue by AramC92** [trivago/prettier-plugin-sort-imports#55]
File Imports or destructured imports get duped after formatting if they're commented at the beginning of the file.

I have the following config:
```json
{
  "importOrder": [
    "^@k9/(.*)$",
    "^@(.*)$",
    "^[./]"
  ],
  "importOrderSeparation": true,
  "semi": false,
  "singleQuote": true,
  "printWidth": 80
}

```

![gif](https://user-images.githubusercontent.com/4724637/117536398-69e30780-afc0-11eb-9225-f5705f093584.gif)

**Comment by byara** [comment]
Thanks @AramC92 for reporting this. Could you please provide a sample repo for this issue? It helps a lot in resolving the issue.

**Comment by AramC92** [comment]
Hiya,

Here it is! https://github.com/AramC92/sample-repo-prettier-sort-issue-55

Some of these examples are almost identical, but apparently even one empty line can make the difference...

Added a devcontainer in case it's needed, but it was basically left untouched, the only important thing about it was installing the `dbaeumer.vscode-eslint` extension

Thanks! :)

**Comment by raineorshine** [comment]
Simplest imports to reproduce. No `importOrder` required.

```ts
// import React from 'react'
import React from 'react'
```
