### ISSUE TITLE
line between import and comment

### ISSUE THREAD

**Issue by chiefchief** [trivago/prettier-plugin-sort-imports#58]
Hello, how can i disable line between imports and first comment after imports
I'm using hygen and i don't need line after imports, but formatting file paste this line

**Comment by byara** [comment]
Hey @chiefchief setting `importOrderSeparation` to false in your config should sort without any line break.

**Comment by chiefchief** [comment]
> Hey @chiefchief setting `importOrderSeparation` to false in your config should sort without any line break.

i tried but anyway it mars as issue 
<img width="291" alt="Снимок экрана 2021-06-13 в 16 03 00" src="https://user-images.githubusercontent.com/32684425/121808413-0a33e800-cc61-11eb-8a0b-9ef1dab75818.png">
<img width="298" alt="Снимок экрана 2021-06-13 в 16 03 09" src="https://user-images.githubusercontent.com/32684425/121808414-0acc7e80-cc61-11eb-87b7-da2820eec0b2.png">

**Comment by ayusharma** [comment]
Could you please provide a better image of the problem? I couldn't understand it. Please feel free to open it if the issue still persists. 😃

**Comment by chiefchief** [comment]
@ayusharma but i've provided images and description
with "prettier-plugin-sort-imports" i see eslint issue, and between import and comment have to be whitespace, i need as on first image, without issue
