### ISSUE TITLE
Sort not work with parser: "babel-flow"

### ISSUE THREAD

**Issue by Yammoe** [trivago/prettier-plugin-sort-imports#6]
Here is my .prettierrc.json
`
{
  "singleQuote": true,
  "importOrder": ["^src/(.*)$", "^[./]"],
  "importOrderSeparation": true,
  "printWidth": 120,
  "parser": "babel-flow"
}
`

I try removing `parser` line then it works normally, but it won't sort with the `parser: "babel-flow`. Is this a bug or I was wrong somewhere?

**Comment by ayusharma** [comment]
@Yammoe Thanks the context. I need to check your use case.

**Comment by Yammoe** [comment]
@ayusharma  Is there any update on this? Thanks.

**Comment by ayusharma** [comment]
@Yammoe I'll check in this week. Sorry for the delays.

**Comment by byara** [comment]
Hey @Yammoe the changes are merged and they will be released soon 👍

**Comment by Yammoe** [comment]
Thanks @byara . Waiting for it 😄

**Comment by byara** [comment]
With the release of v2.0.1, this should be fixed. Either prettier will figure out the syntax correctly, or you can use `experimentalBabelParserPluginsList` in your `.prettierrc` to pass the correct parser name.

If there was still problems, you can of course re-open this issue.

**Comment by wityan** [comment]
Hei
I have just tested this in the current Version and I think it is not working any longer. I have created a Repository to demonstrate it, here the link https://github.com/wityan/prettier-import-example-error.

In src/index.jsx the common import should come before the test import.

Is there an error in my config or is something not working anymore?
