### ISSUE TITLE
Join similar import source

### ISSUE THREAD

**Issue by vimutti77** [trivago/prettier-plugin-sort-imports#60]
Hi, it would be nice to join the similar import source. E.g. this:

### Input
```
import one, { two } from './source'
import { three } from './source'
```

### Output
```
import one, { two, three } from './source'
```

Thanks!

**Comment by mkadirtan** [comment]
I think this is out of scope of this plugin. Because it would be altering the text instead of formatting.

**Comment by byara** [comment]
Hey @vimutti77 as also @mkadirtan mentioned, this is out of the scope of this plugin. But if you want to work on this feature, a PR that implements this, is most welcome!
