### ISSUE TITLE
Fails to install with Prettier 2.3.0

### ISSUE THREAD

**Issue by cnorthwood** [trivago/prettier-plugin-sort-imports#61]
Hi there,

Now Prettier 2.3.0 is out, there's an issue installing this. In https://github.com/trivago/prettier-plugin-sort-imports/blob/master/package.json Prettier is listed both as a peerDependency with a version specifier of ^2.2.1 which permits Prettier 2.3.0, but it's also listed as a dependency with an exact version of 2.2.1. I suspect this is a mistake, and it should only be listed as a peerDependency, but right now this causes Yarn to fail to install this as it can't find a version of Prettier to link. Fixing Prettier to 2.2.1 in our package.json when importing this fixes it, but I think the duplication needs to be resolved here too.

Thanks in advance for the help :)

**Comment by robinzachmann** [comment]
I'm facing the same issue 😞

**Comment by jokull** [comment]
Same

**Comment by CoLoDot** [comment]
Same issue :(

**Comment by Abildtoft** [comment]
Same issue

**Comment by Alphavader** [comment]
same - but the fix helped me thanks @cnorthwood cnorthwood

**Comment by Flosrn** [comment]
Same issue here, how can we resolve it without updating the plugin in node_modules ?

**Comment by sauldeleon** [comment]
Another possible way to fix, but its just another workarround...

add `resolutions` section like

```json
  "resolutions": {
    "prettier": "2.2.1"
  },
```

But the best solution is remove the dependency and just left the peerDependency, right?
