### ISSUE TITLE
How to handle styles import ? .css .scss .less

### ISSUE THREAD

**Issue by franxois** [trivago/prettier-plugin-sort-imports#70]
Hello,

i can't find how to place styles import at the end. Is it possible ? Maybe it can be usefull to write more config exemple in the readme ?

**Comment by timiles** [comment]
Could you just specify a regex for these files last in your importOrder? Something like `"^[.]/[-a-zA-Z0-9_]+[.](css|scss|less)$"` ?

**Comment by franxois** [comment]
If I use

``` "importOrder": ["(c|le|sc)ss$", "^[./]"], ``` It places the style in second, between lib import and local import

With

``` "importOrder": [".+(?<!(c|le|sc)ss)$", "^[./]"], ``` 
or
``` "importOrder": ["(c|le|sc)ss$"], ``` 

It places style at last, but lib and relative import are in the same group. I can't manage to get lib, local import and styles

**Comment by timiles** [comment]
In my project I've managed to get around issues like this by having one group as a negative lookahead of all the other groups:

e.g.

```
  // (...) some rules first
  "^?!(components/|containers/|[.])", // negative lookahead
  "^components/",
  "^containers/",
  // (...) handle other siblings or parent imports
  "^[.]/[-a-zA-Z0-9_]+[.](css|scss|less)$" // end with css etc
```

to ensure that everything not in my `components` or `containers` folders, nor starting with `.` match in the first group, then I have the explicit regexes in the order I like them, ending with the .css etc

Does that help?

**Comment by ayusharma** [comment]
Hi @franxois, thanks for the issue. I think @timiles 's answer should work. If it doesn’t then please feel free to open it again.

**Comment by phongpt156** [comment]
Hi @ayusharma, @timiles 's answer is not working

**Comment by phongpt156** [comment]
@franxois you could try 
```
"importOrder": ["^[./].*(?<!.scss)$", "(c|le|sc)ss$"]
```

**Comment by phongpt156** [comment]
@franxois you could try:
```
"importOrder": ["^[./].*(?<!(c|le|sc)ss)$", "(c|le|sc)ss$"]
```

**Comment by brvnonascimento** [comment]
@phongpt156 you're a life saver!

**Comment by brvnonascimento** [comment]
@phongpt156 you're a lifesaver!

**Comment by alimtunc** [comment]
`"^./*.*.scss"` doest the tricks for me

**Comment by sekoyo** [comment]
I do:

```
importOrder:
  [
    '^src/(.*)$',
    "^[./].*(?<!\\.(c|le|sc)ss)$", // Relative that doesn't end in style file
    "^[^./].*\\.(c|le|sc)ss$", // Non-relative CSS
    "^[./].*\\.(c|le|sc)ss$", // Relative CSS
  ]
  ```
  
  So that the import order is like:
  
- NPM packages
- absolute `src/...` (I have `baseUrl: "."` in my tsconfig.json)
- CSS from NPM packages
- Relative imported CSS
